os: osx

language: objective-c

python:
  - '3.4'

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew install python3

install:
  - pip install -r requirements.txt
  - pip install pytest-cov

script:
  - py.test --cov-report term-missing --cov=project_cron
